//
//  main.m
//  TaskPortHaxxApp
//
//  Created by Duy Tran on 24/10/25.
//

#import <UIKit/UIKit.h>
#import "AppDelegate.h"
#include "Header.h"
// These are provided by mig
#include "mach_exc.h"
#include "mach_excServer.h"

int num_exceptions_handled = 0;
kern_return_t catch_mach_exception_raise_state_identity (mach_port_t exception_port,
                                                         mach_port_t thread,
                                                         mach_port_t task,
                                                         exception_type_t exception,
                                                         mach_exception_data_t code,
                                                         mach_msg_type_number_t codeCnt,
                                                         int *flavor,
                                                         const thread_state_t old_state_,
                                                         mach_msg_type_number_t old_state_cnt,
                                                         thread_state_t new_state_,
                                                         mach_msg_type_number_t *new_state_cnt)
{
    printf("exception handler raise state - exception %d\n", exception);
    if (*flavor != ARM_THREAD_STATE64) {
        return KERN_FAILURE;
    }
    
    if (num_exceptions_handled == 0) {
        printf("got task port: %d\n", task);
        GlobalChildTaskPort = task;
        GlobalChildThreadPort = thread;
    }
    
    // sleep forever
    const arm_thread_state64_t *old_state = (const arm_thread_state64_t*)old_state_;
    arm_thread_state64_t *new_state = (arm_thread_state64_t*)new_state_;
    memcpy(new_state, old_state, sizeof(arm_thread_state64_t));
    new_state->__x[0] = 10;
    new_state->__x[1] = 0x4141414140 + exception;
    void *symbol = dlsym(RTLD_DEFAULT, "sleep");
    void *pc = ptrauth_sign_unauthenticated(ptrauth_strip(symbol, ptrauth_key_function_pointer), ptrauth_key_function_pointer, 0);
    //void *lr = ptrauth_strip(symbol, ptrauth_key_function_pointer);
    __darwin_arm_thread_state64_set_pc_fptr(*new_state, pc);
    //__darwin_arm_thread_state64_set_lr_fptr(*new_state, pc);
    printf("resume address: %p\n", pc);
    *new_state_cnt = old_state_cnt;
    
//    pid_t pid = 0;
//    kern_return_t kr = pid_for_task(task, &pid);
//    NSCAssert(kr == KERN_SUCCESS, @"pid_for_task failed: %d", kr);ap_register failed: %d", kr);
    
    // Test Reading Memory
    task = psychicpaper_proxy(task);
    kern_return_t kr;
    pc = ptrauth_strip(pc, ptrauth_key_function_pointer);
    printf("reading memory at pc: 0x%llx\n", (uint64_t)pc);
    uint8_t buffer[16];
    mach_vm_size_t size = sizeof(buffer);
    kr = vm_read_overwrite(task, (vm_address_t)pc, size, (mach_vm_address_t)buffer, &size);
    if (kr == KERN_SUCCESS) {
        printf("Read %llu bytes:\n", size);
        for (mach_vm_size_t i = 0; i < size; i++) {
            printf("%02x ", buffer[i]);
        }
        printf("\n");
    } else {
        printf("vm_read_overwrite failed: %s\n", mach_error_string(kr));
    }
    
    num_exceptions_handled++;
    return KERN_SUCCESS;
}

extern boolean_t mach_exc_server (mach_msg_header_t *msg, mach_msg_header_t *reply);
static void exception_server(mach_port_t exceptionPort, BOOL shouldExitOnException) {
    mach_msg_return_t rt;
    __Request__mach_exception_raise_state_identity_t msg;
    __Reply__mach_exception_raise_state_identity_t reply;
    BOOL handled = NO;
 
    printf("exception server starting\n");
    do {
        rt = mach_msg((mach_msg_header_t *)&msg, MACH_RCV_MSG, 0, sizeof(union __RequestUnion__mach_exc_subsystem), exceptionPort, 0, MACH_PORT_NULL);
        assert(rt == MACH_MSG_SUCCESS);
        // Call out to the mach_exc_server generated by mig and mach_exc.defs.
        // This will in turn invoke one of:
        // mach_catch_exception_raise()
        // mach_catch_exception_raise_state()
        // mach_catch_exception_raise_state_identity()
        // .. depending on the behavior specified when registering the Mach exception port.
        handled = mach_exc_server((mach_msg_header_t *)&msg, (mach_msg_header_t *)&reply);
 
        // Send the now-initialized reply
        rt = mach_msg((mach_msg_header_t *)&reply, MACH_SEND_MSG, reply.Head.msgh_size, 0, MACH_PORT_NULL, 0, MACH_PORT_NULL);
        assert(rt == MACH_MSG_SUCCESS);
    } while (!shouldExitOnException || !handled);
}

mach_port_t setup_exception_server(void) {
    mach_port_t server_port;
    kern_return_t kr = mach_port_allocate(mach_task_self(), MACH_PORT_RIGHT_RECEIVE, &server_port);
    assert(kr == KERN_SUCCESS);
    kr = mach_port_insert_right(mach_task_self(), server_port, server_port, MACH_MSG_TYPE_MAKE_SEND);
    assert(kr == KERN_SUCCESS);
    kr = bootstrap_register(bootstrap_port, "com.kdt.taskporthaxx.exception_server", server_port);
    assert(kr == KERN_SUCCESS);
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        exception_server(server_port, NO);
    });
    return server_port;
}

// unused
kern_return_t catch_mach_exception_raise_state (mach_port_t exception_port,
                                                exception_type_t exception,
                                                const mach_exception_data_t code,
                                                mach_msg_type_number_t code_cnt,
                                                int *flavor,
                                                const thread_state_t old_state_,
                                                mach_msg_type_number_t old_state_cnt,
                                                thread_state_t new_state_,
                                                mach_msg_type_number_t *new_state_cnt)
{
    // unused
    return KERN_FAILURE;
}
kern_return_t catch_mach_exception_raise (mach_port_t exception_port,
                                         mach_port_t thread,
                                         mach_port_t task,
                                         exception_type_t exception,
                                         mach_exception_data_t code,
                                         mach_msg_type_number_t codeCnt) {
   printf("catch_mach_exception_raise called\n");
   return KERN_FAILURE;
}
