//
//  main.m
//  TaskPortHaxxApp
//
//  Created by Duy Tran on 24/10/25.
//

#import <UIKit/UIKit.h>
#import "AppDelegate.h"
#include "Header.h"
// These are provided by mig
#include "mach_exc.h"
#include "mach_excServer.h"

BOOL done = NO;

kern_return_t catch_mach_exception_raise_state (mach_port_t exception_port,
                                                exception_type_t exception,
                                                const mach_exception_data_t code,
                                                mach_msg_type_number_t code_cnt,
                                                int *flavor,
                                                const thread_state_t old_state_,
                                                mach_msg_type_number_t old_state_cnt,
                                                thread_state_t new_state_,
                                                mach_msg_type_number_t *new_state_cnt)
{
    NSLog(@"exception handler raise state - exception %d", exception);
    if (*flavor == ARM_THREAD_STATE64) {
        const arm_thread_state64_t *old_state = (const arm_thread_state64_t*)old_state_;
        if (done) {
            return KERN_FAILURE;
        }
        done = YES;
        arm_thread_state64_t *new_state = (arm_thread_state64_t*)new_state_;
        NSLog(@"fault address: %p", (void*)old_state->__pc);
        memcpy(new_state, old_state, sizeof(arm_thread_state64_t));
        __darwin_arm_thread_state64_set_pc_fptr(*new_state, (void *)0x4141414100);
        __darwin_arm_thread_state64_set_lr_fptr(*new_state, (void *)0x4242424200);
        for (int i = 0; i < 29; i++) {
            new_state->__x[i] = 0x4141414100 + i;
        }
        NSLog(@"resume address: %p", (void*)new_state->__pc);
        *new_state_cnt = old_state_cnt;
        return KERN_SUCCESS;
    }
    return KERN_FAILURE;
}

// unused, just here to satisfy the linker / mig bits
kern_return_t catch_mach_exception_raise_state_identity (mach_port_t exception_port,
                                                         mach_port_t thread,
                                                         mach_port_t task,
                                                         exception_type_t exception,
                                                         mach_exception_data_t code,
                                                         mach_msg_type_number_t codeCnt,
                                                         int *flavor,
                                                         const thread_state_t old_state,
                                                         mach_msg_type_number_t old_stateCnt,
                                                         thread_state_t new_state,
                                                         mach_msg_type_number_t *new_stateCnt)
{
    // unused
    return KERN_FAILURE;
}
 
kern_return_t catch_mach_exception_raise (mach_port_t exception_port,
                                          mach_port_t thread,
                                          mach_port_t task,
                                          exception_type_t exception,
                                          mach_exception_data_t code,
                                          mach_msg_type_number_t codeCnt)
{
    // unused
    return KERN_FAILURE;
}
 
extern boolean_t mach_exc_server (mach_msg_header_t *msg, mach_msg_header_t *reply);
static void exception_server(mach_port_t exceptionPort)
{
    mach_msg_return_t rt;
    mach_msg_header_t *msg;
    mach_msg_header_t *reply;
 
    msg = malloc(sizeof(union __RequestUnion__mach_exc_subsystem));
    reply = malloc(sizeof(union __ReplyUnion__mach_exc_subsystem));
    NSLog(@"server starting");
    while (1) {
        rt = mach_msg(msg, MACH_RCV_MSG, 0, sizeof(union __RequestUnion__mach_exc_subsystem), exceptionPort, 0, MACH_PORT_NULL);
        assert(rt == MACH_MSG_SUCCESS);
 
        NSLog(@"server received message");
        
        // Call out to the mach_exc_server generated by mig and mach_exc.defs.
        // This will in turn invoke one of:
        // mach_catch_exception_raise()
        // mach_catch_exception_raise_state()
        // mach_catch_exception_raise_state_identity()
        // .. depending on the behavior specified when registering the Mach exception port.
        mach_exc_server(msg, reply);
 
        // Send the now-initialized reply
        rt = mach_msg(reply, MACH_SEND_MSG, reply->msgh_size, 0, MACH_PORT_NULL, 0, MACH_PORT_NULL);
        assert(rt == MACH_MSG_SUCCESS);
    }
}

int main_child(int argc, char * argv[]) {
    // parent process
    pid_t pid;
    char ppid_str[16];
    snprintf(ppid_str, sizeof(ppid_str), "%d", getpid());
    
    char *child_argv[] = { argv[0], "-parent", ppid_str, NULL };
    int status = posix_spawn(&pid, child_argv[0], NULL, NULL, child_argv, environ);
    if (status != 0) {
        perror("posix_spawn child failed");
        return 1;
    }
    printf("Child process spawned with PID: %d\n", pid);
    
    mach_port_t exception_port = MACH_PORT_NULL;
    do {
        kern_return_t kr = bootstrap_look_up(bootstrap_port, "com.kdt.taskporthaxx.exception_server", &exception_port);
        if (kr == KERN_SUCCESS) {
            break;
        }
        usleep(10000);
    } while(exception_port == MACH_PORT_NULL);
    
    posix_spawnattr_t attr;
    if(posix_spawnattr_init(&attr) != 0) {
        perror("posix_spawnattr_init");
        return 1;
    }
    if(getppid() == 1) {
        if(posix_spawnattr_set_launch_type_np(&attr, 1) != 0) {
            perror("posix_spawnattr_set_launch_type_np");
            return 1;
        }
    } else {
        printf("Not launched by launchd, might not work\n");
    }
    
    posix_spawnattr_setexceptionports_np(&attr,
        EXC_MASK_ALL,
        exception_port,
        EXCEPTION_STATE | MACH_EXCEPTION_CODES,
        ARM_THREAD_STATE64);
    
    if(posix_spawnattr_setflags(&attr, POSIX_SPAWN_SETEXEC) != 0) {
        perror("posix_spawnattr_set_flags");
        return 1;
    }
    
    // /System/Library/CoreServices/SpringBoard.app/SpringBoard"
    char *argv2[] = { argv[1], "-parent", ppid_str, NULL };
    posix_spawn(NULL, argv2[0], NULL, &attr, argv2, environ);
    perror("posix_spawn");
    return 0;
}

int main(int argc, char * argv[]) {
    if (argc == 2) {
        return main_child(argc, argv);
    } else if (argc == 3) {
        mach_port_t server_port;
        kern_return_t kr = mach_port_allocate(mach_task_self(), MACH_PORT_RIGHT_RECEIVE, &server_port);
        assert(kr == KERN_SUCCESS);
        kr = mach_port_insert_right(mach_task_self(), server_port, server_port, MACH_MSG_TYPE_MAKE_SEND);
        assert(kr == KERN_SUCCESS);
        kr = bootstrap_register(bootstrap_port, "com.kdt.taskporthaxx.exception_server", server_port);
        assert(kr == KERN_SUCCESS);
        exception_server(server_port);
        return 0;
    }
    
    NSString * appDelegateClassName;
    @autoreleasepool {
        // Setup code that might create autoreleased objects goes here.
        appDelegateClassName = NSStringFromClass([AppDelegate class]);
    }
    return UIApplicationMain(argc, argv, nil, appDelegateClassName);
}
